global:
  resolve_timeout: 10s

route:
  receiver: 'gmail-notifications'

receivers:
- name: 'gmail-notifications'
  email_configs:
  - to: sample@gmail.com
    from: sample@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: sample@gmail.com
    auth_identity: sample@gmail.com
    auth_password: your_password
    send_resolved: true